routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::delete('requests', 'RequestController@delete')->name('requests.delete');
Route::get('tools/{cat}', 'ToolController@catid');
Route::get('toolsCat', 'ToolController@toolsCat');

Route::resources([
	'/categories' =>'CategoryController',
	'/tools' => 'ToolController',
	'/requests' => 'RequestController',
	'/transactions'=> 'TransactionController'
]);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
	use SoftDeletes;
    protected $fillable = ['name', 'image', 'description'];

    public function tools(){
    	return $this->hasMany('App\Tool');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Tool;
use App\Tool_status;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;


class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('viewAny', Category::class);
        
        $categories = Category::all();
         $tools = Tool::all();
        foreach($categories as $category){
            // dd($category->id);
            $category->total= DB::table('tools')->where('category_id', $category->id)->count();
            $category->save();
        }
        foreach($categories as $category){
            // dd($category->id);
            $category->available= DB::table('tools')->where('category_id', $category->id)
            ->where('tool_status_id', 1)->count();
            $category->save();
        }
        return view('categories.index')
        ->with('categories', Category::all())
        ->with('tools', Tool::all());
    }
// }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Category::class);
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Category::class);
        $validatedData = $request->validate([
            'name'=> 'required|unique:categories,name',
            'image'=> 'required|image|max:2000',
            'description'=> 'required'
        ]);
        // $path = $request->file('image')->store('public/products');
        // $url = Storage::url($path);
        $category = new Category($validatedData);
        // $category->image = $url;

        $path=$request->file('image');
        $path_name=time().".".$path->getClientOriginalExtension();
        $destination = "image/";
        $path->move($destination, $path_name);
        $category->image = $destination.$path_name;

        $category->save();
        return redirect(route('categories.index'))
        ->with('message', "Category {$category->name} is added successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {   
        $this->authorize('view', $category);
       
        $tools = Tool::all();
        $tools = Tool::all();
        $count = collect($tools)->where('category_id', $category->id)->where('tool_status_id',1)->count();
        $count_total = collect($tools)->where('category_id', $category->id)->count();
        
        $category->toolcode = strtoupper(Str::random(10));
        $category->controlno =$category->id.'-'.$category->toolcode;

        $tools= Tool::all();
        
            
        return view('categories.show')
            ->with('category', $category)
            ->with('tools', Tool::all()->where('category_id', $category->id))
            ->with('toolstatuses', Tool_status::all())
            ->with('count', $count)
            ->with('count_total', $count_total);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $this->authorize('update', $category);
        return view('categories.partials.showmodal')->with('category', $category)
        ;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->authorize('update', $category);
        $validatedData = $request->validate([
            'name'=> 'required|unique:categories,name',
            'image'=> 'image|max:2000',
            'description'=> 'required'
        ]);
        $category->update($validatedData);
        $path = $request->file('image');

        if($path != ""){

        $path_name=time().".".$path->getClientOriginalExtension();
        $destination = "image/";
        $path->move($destination, $path_name);
        $category->image = $destination.$path_name;
        }
        $category->save();
        return redirect(route('categories.index', $category->id))
        ->with('message', "Category {$category->name} is edited successfully");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $this->authorize('delete', $category);

        $tools = Tool::all();
        $count_total = collect($tools)->where('category_id', $category->id)->count();
        if($count_total === 0)
            {
                $category->delete();
                return redirect(route('categories.index'))
                ->with('message',"Category {$category->name} has been deleted")
                ->with('alert','danger'); 
            }
                return back()
                ->with('message',"Category {$category->name} cannot be deleted")
                ->with('alert','danger');; 
    }

}

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container-fluid">
		@includeWhen(Session::has('message'), 'partials.alert')
		@can('isAdmin')
		<div class="row">
		  	<div class="col-3 my-1">
		    	<div class="list-group" id="list-tab" role="tablist">
		      		<a 
		      			class="list-group-item list-group-item-action active" 
		      			id="list-home-list" 
		      			data-toggle="list" 
		      			href="#list-home" 
		      			role="tab" 
		      			aria-controls="home"
		      		>
		      			Categories
		      		</a>

		     		<a 
		     			class="list-group-item list-group-item-action" 
		     			id="list-profile-list" 
		     			data-toggle="list" 
		     			href="#list-profile" 
		     			role="tab" 
		     			aria-controls="profile"
		     		>
		     		Create Category
		     		</a>	
		    	</div>
		  	</div>
		@endcan
		  	<div class="col-9 mx-auto">
		    	<div class="tab-content" id="nav-tabContent">
		      		<div 
		      			class="tab-pane fade show active" 
		      			id="list-home" 
		      			role="tabpanel" 
		      			aria-labelledby="list-home-list"
		      		>
						@foreach($categories as $category)
							<?php 
								$count = collect($tools)
									->where('category_id', $category->id)
									->where('tool_status_id',1)
									->count();
								$count_total = collect($tools)
									->where('category_id', $category->id)
									->count();
							?>
							{{-- card start --}}
								<div class="card border-secondary text-center col-lg-3 col-md-3 col-sm-6 d-inline-block mx-3 my-1">
									@include('categories.partials.card-body')
									<div class="card-footer bg-transparent">
										<a href="{{route('categories.show', $category->id)}}" class="btn btn-sm btn-outline-success my-1 w-100">View</a>	
										@can('isAdmin')
											{{-- showmodal --}}
											@include('categories.partials.showmodal')
											{{-- delete --}}
											@include('categories.partials.delete')
										@endcan
									</div>	
								</div>
							{{-- card end --}}
						@endforeach
					</div>

		     		<div 
		     			class="tab-pane fade" 
		     			id="list-profile" 
		     			role="tabpanel" 
		     			aria-labelledby="list-profile-list"
		     		>
		     			<div class="col-9">
		     				<h1 class="text-center">
		     					Add Category
		     				</h1>
		     				{{-- start form --}}
								<form action="{{route('categories.store')}}" method="post" enctype="multipart/form-data">
									@csrf
									@include('categories.partials.form')	
								</form>
							{{-- end form --}}
		     			</div>
		     		</div>
		    	</div>
		  	</div>
		</div>
	</div>
@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		@includeWhen(Session::has('message'), 'partials.alert')
		<div class="row">
			<div class="col-3 col-sm-5 col-lg-3">
				<div class="card border-secondary text-center mx-2 my-1">
					<div class="card-body text-dark">
						<div class="card-body text-dark">
							{{-- category name --}}
							<div class="card-title text-center">
								<h4 class="card-name">
									{{$category->name}}
								</h4>
								<br>
								<h6>Current Available: <strong>{{$count}}/{{$count_total}}</strong></h6>
							</div>
							{{-- end category name --}}

							{{-- description start --}}
							<div class="card-text text-center">
								<small>{{$category->description}}</small>
							</div>
							{{-- description end --}}
						</div>
					</div>
					<div class="card-footer">		
						@can('isAdmin')
						{{-- showmodal --}}
						@include('categories.partials.showmodal')

						{{-- delete --}}
						@include('categories.partials.delete')
						@endcan
					</div>

				</div>
				@can('isAdmin')
				<h4 class="text-center">Control code</h4>
				<form action="{{route('tools.store')}}" method="post" enctype="multipart/form-data">
					@csrf
					<div class="input-group mb-3">
					 	<div class="input-group-prepend">
					    {{-- <span class="input-group-text" id="basic-addon1" name="">{{$category->id}}-</span> --}}
					</div>
					  	<input type="text" class="form-control " name="toolcode" id="toolcode" value="{{$category->controlno}}" readonly>
					</div>
					<div class="d-block">
						<h4 class="text-center">Tool Model</h4>
						<select name="category_id" id="category_id" class="form-control form-control-sm" readonly>
						<option value="{{$category->id}}">{{$category->name}} </option>
						</select>
					</div>
					<div class="d-block">
						<h4 class="text-center">Tool Name</h4>
						 <input type="text" name="name" id="name" class="form-control form-control-sm">
						 <input type="file" name="image" id="image" class="form-control-file form-control-sm">
						<h4 class="text-center">Tool Description</h4>
                        <textarea name="description" id="description" class="form-control form-control-sm"></textarea>
                        <button class="btn btn-outline-dark text-center my-1 w-100">Create Tool</button>
					</div>	
				</form>
				@endcan
			</div>
			<div class="col-9 col-sm-7 col-lg-9	">
				@foreach($tools as $tool)
					@if ($category->id === $tool->category_id)
							{{-- product card start --}}
							<div class="col-12 col-lg-3 d-inline-block mx-1 my-1 text-center card-category">
								<div class="card  border-secondary">
									<img src="{{asset($tool->image)}}" alt="" class="card-img-top my-1" height="150" width="250">
									<div class="card-body text-dark">
										<h5 class="card-title ">
											{{$tool->name}}
										</h5>
										<p class="card-text">
											{{$tool->toolcode}}
										</p>
										<p class="card-text mb-0">
											<span class="badge badge-info">
												{{$tool->category->name}}
											</span>
										</p>
										<p class="card-text mb-0">
											<span class="badge badge-{{$tool->tool_status_id === 1 ? "success" : ($tool->tool_status_id === 2 ? "info" : "warning")}}">
														{{$tool->tool_status->name}}
											</span>
										</p>
										@cannot('isAdmin')
										<form action="{{route('requests.update', $tool->id)}}" method="post">
											@csrf
											@method('PUT')
											<button class="
													btn 
													btn-sm 
													btn-outline-{{$tool->tool_status_id!==1 ? "dark" : "success"}} w-100 mt-1" 
													{{$tool->tool_status_id!==1 ? "disabled" : ""}}
													>{{$tool->tool_status_id!==1 ? "Not Available" : "Request"}}
									</button>
										</form>
										@endcannot
									</div>
									@can('isAdmin')
										<div class="card-footer bg-transparent text-center">
											@include('tools.partials.editmodal')
											@include('tools.partials.delete-form')
										</div>
									@endcan
								</div>
							</div>
							{{-- product card end --}}
					@endif
				@endforeach
			</div>
		</div>
	</div>
@endsection