routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::delete('requests', 'RequestController@delete')->name('requests.delete');
Route::get('tools/{cat}', 'ToolController@catid');
Route::get('toolsCat', 'ToolController@toolsCat');

Route::resources([
	'/categories' =>'CategoryController',
	'/tools' => 'ToolController',
	'/requests' => 'RequestController',
	'/transactions'=> 'TransactionController'
]);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
	use SoftDeletes;
    protected $fillable = ['name', 'image', 'description'];

    public function tools(){
    	return $this->hasMany('App\Tool');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Tool;
use App\Tool_status;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;


class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('viewAny', Category::class);
        
        $categories = Category::all();
         $tools = Tool::all();
        foreach($categories as $category){
            // dd($category->id);
            $category->total= DB::table('tools')->where('category_id', $category->id)->count();
            $category->save();
        }
        foreach($categories as $category){
            // dd($category->id);
            $category->available= DB::table('tools')->where('category_id', $category->id)
            ->where('tool_status_id', 1)->count();
            $category->save();
        }
        return view('categories.index')
        ->with('categories', Category::all())
        ->with('tools', Tool::all());
    }
// }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Category::class);
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Category::class);
        $validatedData = $request->validate([
            'name'=> 'required|unique:categories,name',
            'image'=> 'required|image|max:2000',
            'description'=> 'required'
        ]);
        // $path = $request->file('image')->store('public/products');
        // $url = Storage::url($path);
        $category = new Category($validatedData);
        // $category->image = $url;

        $path=$request->file('image');
        $path_name=time().".".$path->getClientOriginalExtension();
        $destination = "image/";
        $path->move($destination, $path_name);
        $category->image = $destination.$path_name;

        $category->save();
        return redirect(route('categories.index'))
        ->with('message', "Category {$category->name} is added successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {   
        $this->authorize('view', $category);
       
        $tools = Tool::all();
        $tools = Tool::all();
        $count = collect($tools)->where('category_id', $category->id)->where('tool_status_id',1)->count();
        $count_total = collect($tools)->where('category_id', $category->id)->count();
        
        $category->toolcode = strtoupper(Str::random(10));
        $category->controlno =$category->id.'-'.$category->toolcode;

        $tools= Tool::all();
        
            
        return view('categories.show')
            ->with('category', $category)
            ->with('tools', Tool::all()->where('category_id', $category->id))
            ->with('toolstatuses', Tool_status::all())
            ->with('count', $count)
            ->with('count_total', $count_total);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $this->authorize('update', $category);
        return view('categories.partials.showmodal')->with('category', $category)
        ;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->authorize('update', $category);
        $validatedData = $request->validate([
            'name'=> 'required|unique:categories,name',
            'image'=> 'image|max:2000',
            'description'=> 'required'
        ]);
        $category->update($validatedData);
        $path = $request->file('image');

        if($path != ""){

        $path_name=time().".".$path->getClientOriginalExtension();
        $destination = "image/";
        $path->move($destination, $path_name);
        $category->image = $destination.$path_name;
        }
        $category->save();
        return redirect(route('categories.index', $category->id))
        ->with('message', "Category {$category->name} is edited successfully");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $this->authorize('delete', $category);

        $tools = Tool::all();
        $count_total = collect($tools)->where('category_id', $category->id)->count();
        if($count_total === 0)
            {
                $category->delete();
                return redirect(route('categories.index'))
                ->with('message',"Category {$category->name} has been deleted")
                ->with('alert','danger'); 
            }
                return back()
                ->with('message',"Category {$category->name} cannot be deleted")
                ->with('alert','danger');; 
    }

}

resources/views/categories/partials/card-body.blade.php
{{-- image start--}}
<img src="{{$category->image}}"alt="" class="card-img-top my-1" id="sample" height="200" width="250">
	{{-- image end --}}
<div class="card-body text-dark">
	{{-- category name --}}
	<div class="card-title text-center">
		<h4 class="card-name">
			{{$category->name}}
		</h4>
		<h5>Current Available:<strong> {{$count}}/{{$count_total}}</strong></h5>
	</div>
	{{-- end category name --}}

	{{-- description start --}}
	<div class="card-text text-center">
		<small>{{$category->description}}</small>
	</div>
	{{-- description end --}}
</div>

resources/views/categories/partials/delete.blade.php
<form action="{{route('categories.destroy', $category->id)}}" method="post" class=" my-1">
	@csrf
	@method('DELETE')
	<button class="btn btn-sm btn-outline-danger w-100">Delete</button>
</form>

resources/views/categories/partials/form.blade.php
<label for="name">Category name:</label>
<input 
	type="text" 
	name="name" 
	id="name" 
	class="form-control form-control-sm 
	@error('name') is-invalid @enderror" 
	required
	>
	@error('name')
		<small class="d-block invalid-feedback">
			<strong>{{$message}}</strong>
		</small>
	@enderror
<label for="image">Category image:</label>
<input type="file" name="image" id="image" class="form-control-file form-control-sm" required>

<label for="description">Category description:</label>
<textarea name="description" id="description" cols="30" rows="10" class="form-control form-control-sm" required></textarea>
<button class="btn btn-sm btn-primary mt-3">
	Add Category
</button>

resources/views/categories/partials/showmodal.blade.php
<!-- Button trigger modal -->
{{-- <button type="button" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#staticBackdrop">
  Edit
</button> --}}
<a href="{{route('categories.edit', $category->id)}} {{-- should be directed to product --}}" class="btn btn-sm btn-outline-primary w-100" data-toggle="modal" data-target="#staticBackdrop{{$category->id}}">Edit</a>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop{{$category->id}}" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel{{$category->id}}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel{{$category->id}}">Edit Category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('categories.update', $category->id)}}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    {{-- start form --}}
                        <label for="name">Category name:</label>
                        <input 
                            type="text" 
                            name="name" 
                            id="name" 
                            class="
                                form-control 
                                form-control-sm
                                @error('name') is-invalid @enderror
                                "  
                            value="{{$category->name}}"
                        >
                        @error('name')
                            <small class="d-block invalid-feedback">
                                <strong>{{$message}}</strong>
                            </small>
                        @enderror
                        <label for="image">Category image:</label>
                        <input type="file" name="image" id="image" class="form-control-file form-control-sm @error('image') is-invalid @enderror">
                        @error('image')
                            <small class="d-block invalid-feedback">
                                <strong>{{$message}}</strong>
                            </small>
                        @enderror
                        <label for="description">Category description:</label>
                        <textarea name="description" id="description"class="form-control form-control-sm @error('description') is-invalid @enderror" >{{$category->description}}</textarea>
                        @error('description')
                            <small class="d-block invalid-feedback">
                                <strong>{{$message}}</strong>
                            </small>
                        @enderror
                        {{-- <button class="btn btn-primary">Edit Category</button> --}}
                    
                  {{-- end form --}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                    <button class="btn btn-outline-info">Edit Category</button>
                </div>
            </form>
        </div>
    </div>
</div>